version: '3.8'

services:

  postgres:
    container_name: postgres-container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: recipeBook
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    expose:
      - 5432:5432
    restart: unless-stopped

volumes:
  postgres:
    driver: local